/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC1155Minter,
  IERC1155MinterInterface,
} from "../../../contracts/interfaces/IERC1155Minter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mintToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC1155Minter__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155MinterInterface {
    return new utils.Interface(_abi) as IERC1155MinterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155Minter {
    return new Contract(address, _abi, signerOrProvider) as IERC1155Minter;
  }
}
